version: 2.1

 # Build and Push to ACR
jobs:
  build_backstage:
    docker:
      - image: cimg/node:16.13.0

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: build
          command: |
            yarn install --frozen-lockfile

            # tsc outputs type definitions to dist-types/ in the repo root, which are then consumed by the build
            yarn tsc

            # Build all packages and in the end bundle them all up into the packages/backend/dist folder.
            yarn build

      - run:
          name: docker build 
          command: |
            docker login -u rohitlavu -p 14ff7030-76b3-41b7-8a9e-14b8f0157584

      - run:
          name: docker build 
          command: |
            docker build app packages/backend/Dockerfile .


workflows:
   build_backstage:
     jobs:
       - build_backstage


